packages:
  - apps/*
  
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - nestjs-pino
  - prisma
  - protobufjs
