name: CI

on:
  push:
    branches: [main, prod]
  pull_request:
    types: [opened, edited, synchronize, reopened]
  merge_group:
    types: [checks_requested]

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm

      - name: Generate Prisma Client
        run: pnpm --filter="backend" exec prisma generate

      - name: Check types (backend)
        run: pnpm --filter="backend" exec tsc --noEmit

      - name: Compile GraphQL schema
        run: pnpm --filter="frontend" run compile

      - name: Check types (frontend)
        run: pnpm --filter="frontend" exec tsc --noEmit

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-pnpm
        with:
          install: 'no'

      # NOTE: eslint-config-next 에서 next 모듈을 찾지 못하는 에러를 해결하기 위해 프론트엔드 의존성을 설치합니다.
      - name: Install root and frontend dependencies
        run: pnpm install -w --filter frontend

      - name: Lint pull request title
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "${{ github.event.pull_request.title }}" | pnpm commitlint --verbose

      - name: Check style (Node.js)
        run: git diff --name-only --diff-filter=ACMRUXB origin/main | xargs -r pnpm prettier -c --ignore-unknown --no-error-on-unmatched-pattern

      - name: Lint (Node.js)
        run: git diff --name-only --diff-filter=ACMRUXB origin/main | grep -E "(.ts$|.tsx$|.js$|.jsx$)" | grep -v 'next.config.js$' | xargs -r pnpm eslint

  build-test-backend:
    name: Build Test Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [client, admin]

    steps:
      - uses: actions/checkout@v4

      - name: Check if source code has changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            shared: &shared
              - 'apps/backend/libs/**'
              - 'apps/backend/prisma/**'
              - 'apps/backend/*.json'
              - 'pnpm-lock.yaml'
            client:
              - *shared
              - 'apps/backend/apps/client/**'
            admin:
              - *shared
              - 'apps/backend/apps/admin/**'

      - uses: ./.github/actions/setup-pnpm
        if: ${{ steps.filter.outputs[matrix.target] == 'true' }}

      - name: Generate Prisma Client
        if: ${{ steps.filter.outputs[matrix.target] == 'true' }}
        run: pnpm --filter="backend" exec prisma generate

      - name: Build
        if: ${{ steps.filter.outputs[matrix.target] == 'true' }}
        run: pnpm --filter="backend" build ${{ matrix.target }}

  run-test-backend:
    name: Run Test Backend
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: file:./main.db
      ADMIN_PORT: 4001
      CLIENT_PORT: 4000

    steps:
      - uses: actions/checkout@v4

      - name: Check if source code has changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'apps/backend/**'
              - 'pnpm-lock.yaml'

      - uses: ./.github/actions/setup-pnpm
        if: steps.filter.outputs.backend == 'true'

      - name: Check Prisma Migration
        if: steps.filter.outputs.backend == 'true'
        run: |
          pnpm --filter="backend" exec prisma migrate diff \
            --from-migrations ./prisma/migrations \
            --to-schema-datamodel ./prisma/schema.prisma \
            --shadow-database-url ${{ env.DATABASE_URL }} \
            --exit-code ||
          (echo "::error::Prisma migration is not up to date." \
          "Please run 'pnpm prisma migrate dev' locally and commit the changes." && exit 1)

      - name: Migrate Prisma
        if: steps.filter.outputs.backend == 'true'
        run: pnpm --filter="backend" exec prisma migrate reset --force

      - name: Test
        if: steps.filter.outputs.backend == 'true'
        run: pnpm --filter="backend" test

